-- Enum for voice lines
return {
    NIL = 0,
    FOR_THE_EMPEROR = 1,
    VACUUM_CAPSULE = 2,
    YES = 3,
    NO = 4,
    CRYONIC_ROD = 5,
    POWER_CELL = 6,
    SCRIPTURE = 7,
    GRIMOIRE = 8,
    RELIC = 9,
    HEALTH_BOOSTER = 10,
    MINE = 11,
    AMMO = 12,
    GRENADE = 13,
    PLASTEEL = 14,
    DIAMANTINE = 15,
    FOLLOWING = 16,
    MEDICATE_STATION = 17,
    UNCHARGED_MEDICAE = 18,
    MEDIPACK = 19,
    MEDIPACK_DOWN = 20,
    AMMO_CRATE = 21,
    NEED_AMMO = 22,
    NEED_HEALING = 23,
    LOOK_THERE = 24,
    GO_THERE = 25,
    ENEMY = 26,
    THANKS = 27,
}
